name: Auto add reviewer

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - main
      - master

jobs:
  add-reviewer:
    name: Add reviewer
    uses: book000/templates/.github/workflows/reusable-add-reviewer.yml@6b1a03112ee32f6c00cc934eb486fcea36dfe5e9 # master
