name: Auto add reviewer

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - main
      - master

jobs:
  add-reviewer:
    name: Add reviewer
    uses: book000/templates/.github/workflows/reusable-add-reviewer.yml@76e83535fd3f9ddc99c9333efb8a4f7dd886edd1 # master
