name: Auto add reviewer

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - main
      - master

jobs:
  add-reviewer:
    name: Add reviewer
    uses: book000/templates/.github/workflows/reusable-add-reviewer.yml@249109e57d1bc836c5a4e1bbf4e446ad2c286deb # master
