# Build and test with Node.js. Use the version specified in .node-version

name: Node CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  node-ci:
    name: Node CI
    uses: book000/templates/.github/workflows/reusable-nodejs-ci-pnpm.yml@224a681f582a2bb48934752864be4f4565ca0b23 # master
