# Build and test with Node.js. Use the version specified in .node-version

name: Node CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  node-ci:
    name: Node CI
    uses: book000/templates/.github/workflows/reusable-nodejs-ci-pnpm.yml@1d3c112ba6b8e5ac13c24a8e3892f92b98ea35ac # master
