# Build and test with Node.js. Use the version specified in .node-version

name: Node CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  node-ci:
    name: Node CI
    uses: book000/templates/.github/workflows/reusable-nodejs-ci-pnpm.yml@76e83535fd3f9ddc99c9333efb8a4f7dd886edd1 # master
